NerdDinner/Controllers/DinnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NerdDinner.Helpers;
using NerdDinner.Models;
using PagedList;

namespace NerdDinner.Controllers {

    [HandleErrorWithELMAH]
    public class DinnersController : Controller {

        IDinnerRepository dinnerRepository;

        NerdIdentity _nerdIdentity;



        private NerdIdentity nerdIdentity {
            get { return (_nerdIdentity ?? User.Identity as NerdIdentity);}
        }

        private const int PageSize = 25;

        //
        // Dependency Injection enabled constructors

        public DinnersController()
            : this(new DinnerRepository(),null)
        {
        }

        public DinnersController(IDinnerRepository repository, NerdIdentity nerdIdentity) {
            dinnerRepository = repository;
            _nerdIdentity = nerdIdentity;
                
        }

        //
        // GET: /Dinners/
        //      /Dinners/Page/2
        //      /Dinners?q=term

        public ActionResult Index(string q, int? page) {

            IQueryable<Dinner> dinners = null;

            //Searching?
            if (!string.IsNullOrWhiteSpace(q))
                dinners = dinnerRepository.FindDinnersByText(q).OrderBy(d => d.EventDate);
            else 
                dinners = dinnerRepository.FindUpcomingDinners();

            int pageIndex = page ?? 1;
            return View(dinners.ToPagedList(pageIndex, PageSize));
        }

        //
        // GET: /Dinners/Details/5

        public ActionResult Details(int? id) {
            if (id == null) {
                return new FileNotFoundResult { Message = "No Dinner found due to invalid dinner id" };
            }

            Dinner dinner = dinnerRepository.Find(id.Value);

            if (dinner == null) {
                return new FileNotFoundResult { Message = "No Dinner found for that id" };
            }

            return View(dinner);
        }

        //
        // GET: /Dinners/Edit/5

        [Authorize]
        public ActionResult Edit(int id) {

            Dinner dinner = dinnerRepository.Find(id);

            if (dinner == null)
                return View("NotFound");

            if (!dinner.IsHostedBy(User.Identity.Name))
                return View("InvalidOwner");

            return View(dinner);
        }

        //
        // POST: /Dinners/Edit/5
        [HttpPost, Authorize, ValidateAntiForgeryToken]
        public ActionResult Edit(int id, FormCollection collection) {

            Dinner dinner = dinnerRepository.Find(id);

            if (!dinner.IsHostedBy(User.Identity.Name))
                return View("InvalidOwner");

            try {
                UpdateModel(dinner);

                dinnerRepository.Save();

                return RedirectToAction("Details", new { id=dinner.DinnerID });
            }
            catch {
                return View(dinner);
            }
        }

        //
        // GET: /Dinners/Create

        [Authorize]
        public ActionResult Create() {

            Dinner dinner = new Dinner() {
               EventDate = DateTime.Now.AddDays(7)
            };

            return View(dinner);
        } 

        //
        // POST: /Dinners/Create

        [HttpPost, Authorize, ValidateAntiForgeryToken]
        public ActionResult Create(Dinner dinner) {

            if (ModelState.IsValid) {
                dinner.HostedById = this.nerdIdentity.Name;
                dinner.HostedBy = this.nerdIdentity.FriendlyName;

                RSVP rsvp = new RSVP();
                rsvp.AttendeeNameId = this.nerdIdentity.Name;
                rsvp.AttendeeName = this.nerdIdentity.FriendlyName;

                dinner.RSVPs = new List<RSVP>();
                dinner.RSVPs.Add(rsvp);

                dinnerRepository.InsertOrUpdate(dinner);
                dinnerRepository.Save();

                return RedirectToAction("Details", new { id=dinner.DinnerID });
            }

            return View(dinner);
        }

        //
        // HTTP GET: /Dinners/Delete/1

        [Authorize, ValidateAntiForgeryToken]
        public ActionResult Delete(int id) {

            Dinner dinner = dinnerRepository.Find(id);

            if (dinner == null)
                return View("NotFound");

            if (!dinner.IsHostedBy(User.Identity.Name))
                return View("InvalidOwner");

            return View(dinner);
        }

        // 
        // HTTP POST: /Dinners/Delete/1

        [HttpPost, Authorize]
        public ActionResult Delete(int id, string confirmButton) {

            Dinner dinner = dinnerRepository.Find(id);

            if (dinner == null)
                return View("NotFound");

            if (!dinner.IsHostedBy(User.Identity.Name))
                return View("InvalidOwner");

            dinnerRepository.Delete(id);
            dinnerRepository.Save();

            return View("Deleted");
        }

  
        protected override void HandleUnknownAction(string actionName)
        {
            throw new HttpException(404, "Action not found");
        }

        public ActionResult Lost()
        {
            return View();
        }

        public ActionResult Trouble()
        {
            return View("Error");
        }

        [Authorize]
        public ActionResult My()
        {
            _nerdIdentity = this.nerdIdentity;

            var userDinners = from dinner in dinnerRepository.All
                              where
                                (
                                String.Equals((dinner.HostedById ?? dinner.HostedBy), _nerdIdentity.Name)
                                    ||
                                dinner.RSVPs.Any(r => r.AttendeeNameId == _nerdIdentity.Name || (r.AttendeeNameId == null && r.AttendeeName == _nerdIdentity.Name)) 
                                )
                              orderby dinner.EventDate
                              select dinner;

            return View(userDinners);
        }

        public ActionResult WebSlicePopular()
        {
            ViewData["Title"] = "Popular Nerd Dinners";
            var model = from dinner in dinnerRepository.FindUpcomingDinners()
                                        orderby dinner.RSVPs.Count descending
                                        select dinner;
            return View("WebSlice",model.Take(5));
        }

        public ActionResult WebSliceUpcoming()
        {
            ViewData["Title"] = "Upcoming Nerd Dinners";
            DateTime d = DateTime.Now.AddMonths(2);
            var model = from dinner in dinnerRepository.FindUpcomingDinners()
                        where dinner.EventDate < d
                        orderby dinner.EventDate descending
                    select dinner;
            return View("WebSlice", model.Take(5));
        }

    }
}

NerdDinner/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NerdDinner.Models;
using NerdDinner.Helpers;
using DDay.iCal.Components;
using NerdDinner.Services;
using System.ComponentModel;

namespace NerdDinner.Controllers
{
    [HandleErrorWithELMAH]
    public class ServicesController : Controller
    {
        IDinnerRepository dinnerRepository;

        public ServicesController() : this(new DinnerRepository()){}

        public ServicesController(IDinnerRepository repository)
        {
            dinnerRepository = repository;
        }

        [OutputCache(VaryByParam = "none", Duration = 300)]
        public ActionResult RSS()
        {
            var dinners = dinnerRepository.FindUpcomingDinners();

            if (dinners == null)
                return View("NotFound");

            return new RssResult(dinners.ToList(), "Upcoming Nerd Dinners");
        }

        [OutputCache(VaryByParam = "none", Duration = 300)]
        public ActionResult iCalFeed()
        {
            var dinners = dinnerRepository.FindUpcomingDinners();

            if (dinners == null)
                return View("NotFound");

            return new iCalResult(dinners.ToList(), "NerdDinners.ics");
        }
        
        public ActionResult iCal(int id)
        {
            Dinner dinner = dinnerRepository.Find(id);

            if (dinner == null)
                return View("NotFound");

            return new iCalResult(dinner, "NerdDinner.ics");
        }

        public ActionResult Flair([DefaultValue("html")]string format)
        {
            string SourceIP = string.IsNullOrEmpty(Request.ServerVariables["HTTP_X_FORWARDED_FOR"]) ?
                Request.ServerVariables["REMOTE_ADDR"] :
                Request.ServerVariables["HTTP_X_FORWARDED_FOR"];

            var location = GeolocationService.HostIpToPlaceName(SourceIP);
            var dinners = dinnerRepository.
                FindByLocation(location.Position.Lat, location.Position.Long).
                OrderByDescending(p => p.EventDate).Take(3);

            // Select the view we'll return. Using a switch because we'll add in JSON and other formats later.
            // Will probably extract or refactor this.
            string view;
            switch (format.ToLower())
            {
                case "javascript":
                    view = "JavascriptFlair";
                    break;
                default:
                    view = "Flair";
                    break;
            }

            return View(
                view,
                new FlairViewModel 
                {
                    Dinners = dinners.ToList(),
                    LocationName = string.IsNullOrEmpty(location.City) ? "you" :  String.Format("{0}, {1}", location.City, location.RegionName)
                }
            );
        }
    }
}

NerdDinner/Views/Shared/Lost.cshtml
@{
    ViewBag.Title = "Lost";
}
<h2>
    Confused?</h2>
<p>
    Are you lost? Try taking a look at the complete list of <a href="/Dinners">Upcoming
        Dinners</a>.</p>

NerdDinner/Views/Shared/Results.Mobile.cshtml
@model PagedList.PagedList<NerdDinner.Models.Dinner>
@{
    ViewBag.Title = "Results";
    Layout = "~/Views/Shared/_Layout.Mobile.cshtml";
}
<ul id="Details" data-role="listview" data-inset="true">
    @if (Model == null || Model.Count == 0)
    {
        <li>No Nerd Dinners found!</li>
    }
    else
    {
        foreach (var dinner in Model)
        {
        <li><a href="@Url.RouteUrl("PrettyDetails", new { Id = dinner.DinnerID })">
            @dinner.EventDate.ToString("MMM dd") @HttpUtility.HtmlEncode(dinner.Description)
        </a></li> 
        }
    }
</ul>

NerdDinner/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html> 
<html> 
	<head> 
	    <title>@ViewBag.Title</title> 
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
	    <link rel="stylesheet" href="@Url.Content("~/Content/jquery.mobile-1.0b2.min.css")" />
	    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.6.2.min.js")"></script>
        <script type="text/javascript">
            $(document).bind("mobileinit", function() {
                // As of Beta 1, jQuery Mobile's Ajax navigation does not work in all cases (e.g., on WP7,
                // or when navigating from a mobile to a non-mobile page), hence disabling it.
                $.mobile.ajaxEnabled = false;
            });
        </script>
        <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.mobile-1.0b2.min.js")"></script>
        @RenderSection("HeadArea", required: false)
    </head> 
<body> 
    <div data-role="page" data-theme="b">
	    <div data-role="header">
		    <h1>@ViewBag.Title</h1>
	    </div>
	    <div data-role="content">	
		    @RenderBody()		
	    </div>
    </div>
</body>
</html>

NerdDinner/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta content="Nerd, Dinner, Geek, Luncheon, Dweeb, Breakfast, Technology, Bar, Beer, Wonk"
        name="keywords" />
    <meta name="description" content="Host and promote your own Nerd Dinner free!" />
    <link title="NerdDinner.com" rel="search" type="application/opensearchdescription+xml" href="@Url.Content("~/Services/OpenSearch.ashx")" />
    <link href="@Url.Content("~/Content/Production.css?v=2")" rel="stylesheet" type="text/css" media="screen" />
   
    <link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.11/themes/humanity/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.6.2.min.js" type="text/javascript"></script> 
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.15/jquery-ui.min.js" type="text/javascript"></script> 
    <script src="http://ajax.aspnetcdn.com/ajax/mvc/3.0/jquery.unobtrusive-ajax.min.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/4.0/1/MicrosoftAjax.js" type="text/javascript"></script> 
    <script src="http://ajax.aspnetcdn.com/ajax/mvc/3.0/MicrosoftMvcAjax.js" type="text/javascript"></script> 

    <script type="text/javascript">
       if (typeof jQuery == 'undefined') {
           document.write(unescape("%3Clink href='/Content/themes/base/jquery.ui.all.css' rel='stylesheet' type='text/css'%3E"));
           document.write(unescape("%3Cscript src='/Scripts/jquery-1.6.2.min.js' type='text/javascript'%3E%3C/script%3E"));
           document.write(unescape("%3Cscript src='/Scripts/jquery-ui-1.8.15.min.js' type='text/javascript'%3E%3C/script%3E"));
           document.write(unescape("%3Cscript src='/Scripts/jquery.unobtrusive-ajax.min.js' type='text/javascript'%3E%3C/script%3E"));
           document.write(unescape("%3Cscript src='/Scripts/MicrosoftAjax.js' type='text/javascript'%3E%3C/script%3E"));
           document.write(unescape("%3Cscript src='/Scripts/MicrosoftMvcAjax.js' type='text/javascript'%3E%3C/script%3E"));
       }
   </script>

    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/yepnope.1.0.1-min.js")" type="text/javascript"></script>    
    <script src="@Url.Content("~/Scripts/date.format.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/NerdDinner.js?v=6")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/timepicker_plug/TimePickerAddOn.js")" type="text/javascript"></script>
    <script src="http://www.google-analytics.com/ga.js" type="text/javascript"></script>
    <script src="http://cdn.uservoice.com/javascripts/widgets/tab.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Scripts/timepicker_plug/css/TimePickerAddOn.css")"/>
    <link rel="alternate" type="application/rss+xml" title="NerdDinner.com - Upcoming Dinners" href="@Url.Content("~/Services/RSS")" />
    <link rel="odata.service" title="NerdDinner.com OData Service" href="@Url.Content("~/Services/OData.svc")" />
    <link rel="odata.feed" title="NerdDinner.com OData Service - Dinners" href="@Url.Content("~/Services/OData.svc/Dinners")" />
    @RenderSection("HeadArea", required: false)

    @MvcMiniProfiler.MiniProfiler.RenderIncludes()

</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>
                    <a href="@Url.Content("~/")" title="Nerd Dinner" class="logo"></a>
                </h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LoginStatus")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Find Dinner", "Index", "Home")</li>
                    <li>@Html.ActionLink("Host Dinner", "Create", "Dinners")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("My Dinners", "My", "Dinners")</li>
                    }
                    <li class="last">@Html.ActionLink("About", "About", "Home")</li>
                </ul>
                <a class="feed" href="@Url.Content("~/Services/OData.svc")">
                    <img alt="OData Feed" title="OData Feed" src="@Url.Content("~/Content/Img/icon-odatafeed-28x28.png")" /></a>
                <a class="feed" href="@Url.Content("~/Services/RSS")">
                    <img alt="RSS Feed" title="RSS Feed" src="@Url.Content("~/Content/Img/icon-feed-28x28.png")" /></a>
                <a class="feed" href="@Url.Action("iCalFeed", "Services", null, "webcal") ">
                    <img alt="iCal Calendar Feed for Nerd Dinners" title="iCal Calendar Feed for Nerd Dinners" src="@Url.Content("~/Content/Img/icon-icalfeed-28x28.png")" /></a>
            </nav>
        </header>
        @RenderSection("Masthead", required: false)
        <div id="main" class="clearfix">
            @RenderBody()
        </div>
        <footer>
            Code by <a href="http://www.hanselman.com">Hanselman</a>, <a href="http://weblogs.asp.net/scottgu">
                Guthrie</a>, <a href="http://weblogs.asp.net/jgalloway">Galloway</a>, <a href="http://mourfield.com">
                    Mourfield</a>,<a href="http://www.johnvpetersen.com"> Petersen</a>  and <a href="http://blog.nerdbank.net/">Arnott</a>. JavaScript
            by <a href="http://encosia.com">Dave Ward</a>. ASP.NET MVC by <a href="http://www.haacked.com">
                Haack</a> and friends. Style by <a href="http://michaeldorian.com/">Michael Dorian Bach</a>.<br />
            Source Code at <a href="http://nerddinner.codeplex.com">http://nerddinner.codeplex.com</a>.
            Free Sample Book Chapter and code walkthrough at <a href="http://tinyurl.com/aspnetmvc">
                http://tinyurl.com/aspnetmvc</a>. <br />
                Version: @HttpContext.Current.Application["Version"]
        </footer>
        <script type="text/javascript">
            var pageTracker = _gat._getTracker("UA-6399325-1");
            pageTracker._initData();
            pageTracker._trackPageview();
        </script>



        <script type="text/javascript">
            UserVoice.Tab.show({
                key: 'nerddinner',
                host: 'feedback.nerddinner.com',
                forum: 'general',
                alignment: 'right', /* 'left', 'right' */
                background_color: '#A2CC3B',
                text_color: 'white', /* 'white', 'black' */
                hover_color: '#7A0100',
                lang: 'en' /* 'en', 'de', 'nl', 'es', 'fr' */
            });
        </script>

</body>
</html>

NerdDinner/Views/Shared/_LoginStatus.cshtml
@using NerdDinner;


@if(Request.IsAuthenticated) {
    <text>Welcome <b>@(((NerdIdentity)HttpContext.Current.User.Identity).FriendlyName)</b>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", new { controller = "Account", returnUrl = HttpContext.Current.Request.RawUrl }) ]
}

NerdDinner/Views/Shared/_Masthead.cshtml
<div id="hm-masthead">
    @if (Model == null)
    { 
        <div id="searchBox">
            <div class="search-text">
                Enter your location or <strong>@Html.ActionLink("View All Upcoming Dinners", "Index", "Dinners")</strong>.</div>
            @Html.TextBox("Location")
            <input id="search" type="submit" value="Search" />
        </div>
        
        <script type="text/javascript">
            $("#search").click(ValidateAndFindDinners);

            $("#Location").keypress(function (evt) {
                if (evt.which == 13) {
                    ValidateAndFindDinners();
                }
            });

            function ValidateAndFindDinners() {
                var where = $.trim($get('Location').value);

                if (where.length < 1)
                    return;

                Sys.Application.addHistoryPoint({ 'where': where });

                NerdDinner.FindDinnersGivenLocation(where);
            }
        </script>
    }
</div>